import PDFDocument from 'pdfkit';

const formatCurrency = (value) => {
  const amount = Number(value || 0);
  return `INR ${amount.toLocaleString('en-IN')}`;
};

export const buildReceiptPdfBuffer = async ({
  receiptNumber,
  studentName,
  studentEmail,
  amount,
  paidAt,
  method,
  items = [],
}) => {
  const doc = new PDFDocument({ margin: 48, size: 'A4' });
  const chunks = [];

  return new Promise((resolve, reject) => {
    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    doc.fontSize(20).text('HostelEase Payment Receipt', { align: 'center' });
    doc.moveDown(1);

    doc.fontSize(12).text(`Receipt No: ${receiptNumber || 'N/A'}`);
    doc.text(`Student: ${studentName || 'N/A'}`);
    doc.text(`Email: ${studentEmail || 'N/A'}`);
    doc.text(`Paid On: ${paidAt ? new Date(paidAt).toLocaleString('en-IN') : 'N/A'}`);
    doc.text(`Method: ${method || 'N/A'}`);
    doc.moveDown(1);

    if (items.length > 0) {
      doc.fontSize(12).text('Fee Items', { underline: true });
      doc.moveDown(0.5);
      items.forEach((item) => {
        doc.text(`${item.term || 'Fee'}: ${formatCurrency(item.amount)}`);
      });
      doc.moveDown(0.5);
    }

    doc.fontSize(14).text(`Total Paid: ${formatCurrency(amount)}`, { align: 'right' });
    doc.moveDown(2);

    doc.fontSize(10).fillColor('#64748b').text('This receipt is generated by HostelEase. Please keep it for your records.', {
      align: 'center',
    });

    doc.end();
  });
};
